### ISSUE TITLE
Link to release notes are broken

### ISSUE THREAD

**Issue by AryehGielchinsky** [CaddyBuilds/caddy-cloudflare#10]
Looks like sometime between 2.7.6 and 2.8.0 the link to the release notes broke. It should include a `v` before the version number.

Current/Broken
https://github.com/caddyserver/caddy/releases/tag/2.8.4

Correct
https://github.com/caddyserver/caddy/releases/tag/v2.8.4

**Comment by vkartk** [comment]
Hey, @AryehGielchinsky  thanks for pointing this out! I’ve fixed the link in [Commit fbfd1e9](https://github.com/CaddyBuilds/caddy-cloudflare/commit/fbfd1e9). Really appreciate you catching that! Let me know if you spot anything else. 😊
